# Generated by Django 6.0.5 on 2026-05-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8),
        ),
    ]
