# Generated by Django 6.0.5 on 2026-05-19 11:53

import railway.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0003_trip_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=railway.models.image_path
            ),
        ),
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=railway.models.image_path
            ),
        ),
    ]
